### ISSUE TITLE
Feature requrest: Offloaded postprocessing

### ISSUE THREAD

**Issue by J-Swift** [nzbget-ng/nzbget#45]
First, thank you for taking the mantle and maintaining this fork!

Not sure its been brought up before on this side of the fork, but on the old repo there was this:

https://github.com/nzbget/nzbget/issues/43

I am in a similar boat as the OP of that issue. Running on an underpowered node with good connectivity to a bigger server which would be great to offload to for the postprocessing. Is this still something that isn't likely to be considered?

**Comment by paul-chambers** [comment]
Just didn't want to see it fall on the floor. When there are only two choices,  losing one is not a good thing...  I'm still hoping people will pitch in to help; There's a broader set of work than I can hope to cover in my 'spare' time, and several platforms I'm not that experienced developing for (e.g. Win32).

Yes, I think it makes sense to separate the post-processing from the actual retrieval of the files. However, somehow I doubt that there's a clean dividing line in the `nzbget` code, as it stands. The code looks like it's grown incrementally over time, so there's probably some refactoring needed to have a clean API between the two. Then there's the issue of status reporting, both in the Web UI and client API.

Honestly, there's a fair amount of overlap with the post-processing needed after torrent retrieval, too. It would make sense to have one post-processor to handle whatever was retrieved, wherever it came from (e.g. offload services like put.io, Offcloud, and bitport.io).

There is an existing project called [unpackerr](https://github.com/Unpackerr/unpackerr), though personally, I find the way it works a little... unorthodox. I'd rather 'push' a new download to it to unpack, but the current design seems to poll *arrs to discover what to unpack. Still, it makes sense to me to extend 'unpackerr' rather than to re-invent the entire wheel. Gives me another reason to learn Go, too :)

**Comment by paul-chambers** [comment]
Closing this here, as it's been cloned as [#99](https://github.com/nzbgetcom/nzbget/issues/99) to nzbgetcom/nzbget.
